hmms_and_names: hmms_and_names_example.tsv

viral_faa_list: viral_protein_faa_reps_example.txt
viral_genome_fna_reps: viral_transcript_fna_reps_example.txt
viral_tax: viral_taxonomy_example.tsv

off_target_faa_list: off_target_faa_reps_example.txt
gtdb_bac_tax: /work/microbiome/db/gtdb/gtdb_release214/bac120_taxonomy_r214.tsv
gtdb_arc_tax: /work/microbiome/db/gtdb/gtdb_release214/ar53_taxonomy_r214.tsv
gtdb_proviruses: gtdb_r214_virus_summary_example.tsv

output_dir: outdir # Placeholder directory where all output files will be stored
output_metapackage: output_example.smpkg
